name: panda_jitsu
description: A card-based, cross-platform game made in Flutter.

# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# Read more about iOS versioning at https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2 # access to 'CupertinoIcons'
  flame: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3" # app icon
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app-icon.png"


# For generic Dart info, see https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true # access to material 'Icons'
  assets:
   - assets/images/background/dojo-no-tray.png
   - assets/images/background/dojo.png
   - assets/images/background/frame-with-tray.png
   - assets/images/background/frame.png
   - assets/images/background/help.png
   - assets/images/background/tray.png
   - assets/images/belts/white-belt.png
   - assets/images/belts/yellow-belt.png
   - assets/images/belts/orange-belt.png
   - assets/images/belts/green-belt.png
   - assets/images/belts/blue-belt.png
   - assets/images/belts/red-belt.png
   - assets/images/belts/purple-belt.png
   - assets/images/belts/brown-belt.png
   - assets/images/belts/black-belt.png
   - assets/images/branding/logo-beige.png
   - assets/images/branding/logo-orange.png
   - assets/images/branding/logo-white.png
   - assets/images/modals/instructions.png
   - assets/images/modals/legend.png
   - assets/images/cards/back-side.png
   - assets/images/cards/blue-card.png
   - assets/images/cards/fire-card.png
   - assets/images/cards/fire.png
   - assets/images/cards/green-card.png
   - assets/images/cards/orange-card.png
   - assets/images/cards/purple-card.png
   - assets/images/cards/red-card.png
   - assets/images/cards/sensei-back.png
   - assets/images/cards/snow-card.png
   - assets/images/cards/snow.png
   - assets/images/cards/water-card.png
   - assets/images/cards/water.png
   - assets/images/cards/yellow-card.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Julee
      fonts:
        - asset: assets/fonts/Julee-Regular.ttf